pi: float = 3.141592653589793
e: float = 2.718281828459045

def fabs(x: float) -> float: ...
def sqrt(x: float) -> float: ...
def exp(x: float) -> float: ...
def pow(x: float, y: float) -> float: ...
def log(x: float, base: float = None) -> float: ...
def fmod(x: float, y: float) -> float: ...
def ceil(x: float) -> int: ...
def floor(x: float) -> int: ...
def trunc(x: float) -> int: ...
def frexp(x: float) -> tuple[float, int]: ...
def radians(deg: float) -> float: ...
def degrees(rad: float) -> float: ...
def sin(x: float) -> float: ...
def cos(x: float) -> float: ...
def tan(x: float) -> float: ...
def asin(x: float) -> float: ...
def acos(x: float) -> float: ...
def atan(x: float) -> float: ...
def atan2(y: float, x: float) -> float: ...